### ISSUE TITLE
RegressionTests fail when Double.NaN is method testing arg

### ISSUE THREAD

**Issue by chagmed** [randoop/randoop#120]
randoop newbie seeing RegressionTests fail after `Double.NaN` used as test arg to utility methods.

Running randoop 3.0.4 on Win 7-x64, jdk 8u102x64.

Classpath includes (in order) `junit-4.12.jar;hamcrest-core-1.3.jar;randoop-all-3.0.4.jar`

Snippet of first test failure:
```java
byte[] byte_array1 = MyRandoopTest.toByteArray(Double.NaN);
long long2 = MyRandoopTest.toLong(byte_array1);
// Regression assertion (captures the current behavior of the code)
org.junit.Assert.assertTrue(long2 == (-1L));
```

[MyRandoopTest.zip](https://github.com/randoop/randoop/files/469713/MyRandoopTest.zip)

**Comment by bjkeller** [comment]
Thanks for reporting this problem.  

This is called a *flaky* test, because the behavior changes between contexts. These usually have to do with static variables that are changed in method calls. But, in this case, the issue seems to relate to the note in the documentation of [Double.longBitsToDouble(long)](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#longBitsToDouble(long)), which points out an issue involving the two representations of `NaN`.

**Comment by bjkeller** [comment]
Confirmed by making `toDouble()` private, and adding the method

````java
  public static double getNaN() { return Double.NaN; }
````

to the example class. In this case we get something like

````java
    byte[] byte_array1 = MyRandoopTest.toByteArray(Double.NaN);
    long long2 = MyRandoopTest.toLong(byte_array1);

    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(long2 == 9221120237041090560L);
````

While changing the method to 

````java
  public static double getNaN() { return toDouble(toByteArray(-1)); }
````

gives the test for `-1L` as described in the issue.
