### ISSUE TITLE
Problems in testing a log4j-dependent project

### ISSUE THREAD

**Issue by mdimjasevic** [randoop/randoop#127]
Dear Randoop authors,

I'm trying to test a Java project that depends on log4j with Randoop. I'm not sure if the following error is due to Randoop's limits in testing something that relies on log4j or if it is something else.

In particular, I wanted to test the Remote Invocation Framework project from the SF110 benchmarks: http://www.evosuite.org/experimental-data/sf110/. However, when I run Randoop 3.0.8-prelease on it, I get this:

```
Progress update: test inputs generated=0, failing inputs=0      (Tue Dec 06 03:50:14 CET 2016)log4j:WARN No appenders could be found for logger (org.apache.axiom.om.impl.builder.StAXOMBuilder).
log4j:WARN Please initialize the log4j system properly.
Usage: SimpleHTTPServer [options] <repository>
 Opts: -? this message
```

Does this mean there's a protocol to follow in using log4j, which Randoop is unlikely to successfully follow (because Randoop doesn't specialize in automatically testing protocols)?

**Comment by bjkeller** [comment]
Yes.  Starting with version 3.0.7, Randoop has the ability to add test fixtures, but, for now, there is no way to link the objects in the fixture to the generated test.

**Comment by bjkeller** [comment]
I should amend the previous comment to say that there is no natural way to specify the protocol to Randoop.  However, I expect the following will work:

1. Disable direct calls to protocol methods, as well as calls to any constructor or factory/creator method that uses global state setup by the protocol. Do this using `--omitmethods` to list all protocol methods. 
2. Implement a class to manage the protocol through static variables set by static setup and teardown methods, and include this as an input class. Provide any factory/creator methods you need due to hidden constructors.  Use `--omitmethods` to disable direct calls to the setup and teardown methods.
3. Create a file containing the code for use of the protocol manger class setup methods, and another for the teardown calls.  Use `--junit-before-each` or `--junit-before-all` to give the file name depending on which fixture these files should be added to.

All with some tweaking, and care with the static state of the protocol manager.

**Comment by mdimjasevic** [comment]
@bjkeller, thank you for an extensive comment! However, I am interested in automatic testing where I am oblivious to specifics of a system under test. All I do is provide a list of all classes in the system, paths to its dependencies, and run Randoop on the system.

**Comment by bjkeller** [comment]
So, _if protocol violations could be detected as an error during execution by reflection_, then Randoop would be able to arrive at the protocol. However, this condition is not likely.
