### ISSUE TITLE
Randoop : Unable to load type

### ISSUE THREAD

**Issue by ku244926** [randoop/randoop#186]
D:\software\Randoop>java -ea  -classpath  D:\software\Randoop\randoop-3.0.6\randoop-all-3.0.6.jar;D:\software\Randoop\javaTesting.jar;  randoop.main.Main gentests --testclass=generic.query.generateQue
ry  --timelimit=60
policy = sun.security.provider.PolicyFile@75222b8e

Throwable thrown while handling command: java.lang.Error: Unable to load type "generic.query.generateQuery" due to exception: null
java.lang.Error: Unable to load type "generic.query.generateQuery" due to exception: null
        at randoop.main.ThrowClassNameError.handle(ThrowClassNameError.java:16)
        at randoop.reflection.OperationModel.addClassTypes(OperationModel.java:310)
        at randoop.reflection.OperationModel.createModel(OperationModel.java:144)
        at randoop.main.GenTests.handle(GenTests.java:191)
        at randoop.main.Main.nonStaticMain(Main.java:63)
        at randoop.main.Main.main(Main.java:27)

Randoop failed.
Last sequence under execution: null

**Desc:** While running Randoop , i am getting exception like "Unable to load type "generic.query.generateQuery" due to exception: null ".
can anyone suggest the possible fix..

**Comment by bjkeller** [comment]
My guess is that your classpath is incorrect. Based on what you have provided, the only thing I can say definitively is that you don't need the semicolon (`;`) at the end of the classpath. However, that shouldn't be a problem if the rest is well-formed. I would double-check that the class is actually in the javaTesting.jar file.

Because classpath problems are so common for users, we have put a good deal of effort into improving the messages. I expect that the latest version of Randoop will give you a better message.  If it does not, please post more details because it is something we would like to fix.

Also, the GitHub issue tracker is for reports of problems with Randoop that need to be fixed. The [Randoop Discussion group](https://groups.google.com/forum/#!forum/randoop-discuss) is the best place to ask questions about using Randoop.

**Comment by bjkeller** [comment]
I'm going to go ahead and close this issue.  However, if you need help, please ask.
