### ISSUE TITLE
Randoop not terminating on PlumeLib class

### ISSUE THREAD

**Issue by ariannab** [randoop/randoop#316]
I am using the most recent released Randoop version, 4.0.0.
Randoop doesn't terminate when trying to generate tests for class `plume.UtilMDE` (PlumeLib 1.1.0 - [Link to archive ](https://github.com/mernst/plume-lib/releases/download/v1.1.0/plume-lib-1.1.0.tar.gz)).

Here is the command to reproduce the issue:
`java -ea -cp plume.jar:randoop.jar randoop.main.Main gentests --testclass=plume.UtilMDE --time-limit=900 --stop-on-error-test --junit-output-dir=testdir --flaky-test-behavior=DISCARD --no-regression-tests --log=randoop-log.txt `

The only output I get before the process hangs indefinitely is the following:
```
PUBLIC MEMBERS=153
Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)
```

**Comment by mernst** [comment]
The problem is that Randoop created a test that did not terminate.
See 
https://randoop.github.io/randoop/manual/index.html#nontermination
for some tips on debugging such problems.  The `--log` command-line argument is the easiest.

I looked at file `randoop-log.txt`, and it contained at the end:

```
Successfully created new unique sequence:
java.lang.String str2 = plume.UtilMDE.removeWhitespaceBefore("L\n;\nL;", "");
```

Plume-lib's `removeWhitespaceBefore` routine enters an infinite loop if its second argument is `""`.
I have fixed this problem (see https://github.com/mernst/plume-lib/commit/8eaab56b40bec3128c4ae18bbc03672d66cc9691), so you could use plume-lib from its repository or exclude that method from testing.
