### ISSUE TITLE
Java 9:  "Cannot find the Java compiler. Check that classpath includes tools.jar"

### ISSUE THREAD

**Issue by ericmei** [randoop/randoop#332]
I have the same issue as in https://github.com/randoop/randoop/issues/176
However, I have not been able to solve my issue using the provided instructions.

I run commands such as 
java -ea -classpath "C:\Users\Eric Mei\Downloads\randoop-4.0.0\bin";"C:\Users\Eric Mei\Downloads\randoop-4.0.0\randoop-all-4.0.0.jar" randoop.main.Main gentests --testclass=Utils --time-limit=60

java -ea -classpath "C:\Users\Eric Mei\Downloads\randoop-4.0.0\bin";%RANDOOP_JAR% randoop.main.Main gentests --testclass=Utils --time-limit=60

java -ea -classpath "C:\Users\Eric Mei\Downloads\randoop-4.0.0\bin";%RANDOOP_JAR%;%JAVA_HOME%\lib\tools.jar randoop.main.Main gentests --testclass=Utils --time-limit=60

All of them will generate the same error:

![same error again](https://user-images.githubusercontent.com/13291480/37566799-f2362a7c-2af8-11e8-92a4-0e14065fa034.PNG)

I had placed JAVA_HOME in front of the path variable and set up user variables accordingly.
![java_home at front](https://user-images.githubusercontent.com/13291480/37566822-1b9bb7c4-2af9-11e8-86e7-026c845b82ca.PNG)

![user variables set up](https://user-images.githubusercontent.com/13291480/37566839-581c6fd6-2af9-11e8-87ff-66302c11c8d5.PNG)

The organization of the folder holding the files and the class file inside the bin:
![randoop folder organization](https://user-images.githubusercontent.com/13291480/37566874-dc2d55a6-2af9-11e8-8934-5bfe404cd5d5.PNG)

![inside bin](https://user-images.githubusercontent.com/13291480/37566883-ef2d490e-2af9-11e8-8541-16336c60fca0.PNG)

I'm using windows 10.
Randoop version: 4.0.0

**Comment by mernst** [comment]
I'm sorry that you are having trouble.
The problem generally indicates that Java is incorrectly installed.

Can you provide a reproducible test case?  That would be a set of instructions, including how you installed Java and Randoop, and the program that you are running under Randoop.  Thanks!

**Comment by ericmei** [comment]
It would seem that something is incompatible with Java 9. Upon switching my path to Java 8, I was able to run even the most recent version of Randoop.

**Comment by mernst** [comment]
Thanks for the explanation!  It's very helpful to know that Randoop is not compatible with Java 9.  I have added a note to that effect in the manual.

It's also possible that the problem was the incompatibility between javapath and `JAVA_HOME`, but I have no evidence about that.  

We have kept Randoop compatible with Java 7 and 8 because of users who use Java 7.  We haven't tried Java 9 yet.  But as adoption of Java 9 increases, we'll put that on our roadmap.

Thanks again.

**Comment by rickersilva** [comment]
This is a very noob question, but I have not find a randoop downlaod that contains the bin folder. Not so much experience in java either.

the download folder referred in every tutorial does not have it, however in every screenshot there it is the bin folder. May I create it and that´s it?

I understood that I have to place the class file I wish to generete test for in the bin folder. Is this correct? I only asks because there are hundred of files I need to create tests for, and wan to look into it further.

I´m facing the same error message here. I already set the Path and JAVA_HOME variables.

**Comment by mernst** [comment]
> I have not find a randoop downlaod that contains the bin folder.

This is an old issue that refers to an old version of Randoop.  Randoop no longer has a `bin` folder.  Now it has a `scripts` folder instead.  You can find that in the distribution: [randoop-4.2.1.zip](https://github.com/randoop/randoop/archive/v4.2.1.zip).
I suggest that you use the instructions for the current version of Randoop, rather than older ones.

> I understood that I have to place the class file I wish to generete test for in the bin folder.

No, that is not necessary.  (Nor in the `scripts` folder.)  Can you point out the text that made you believe that, so that we can update the instructions?

(For future reference, when you change the subject by bringing up a completely different topic, please open a new issue.  That helps others who have a similar problem, and it keeps from cluttering the old issues with unrelated discussions.  Thanks!)

**Comment by rickersilva** [comment]
Thnak you Mernst. I´m abuot to try eberything you said. But in the mean time, the download link you sent me is slightly different than the one I found on my own on randoop page and the one that I found doesnot have all those file, only three jars. May be it can be made more accesible.

according to the instruction, I first use this command in the randoop manual

java -Xmx3000m -classpath C:\Users\s1878883\Source\gcms-baas-card\gateway\build\classes\java\main\com\bns\baas\card\gateway\account\CreditCardFindAll.class:$(C:\randoop-4.2.1\randoop-all-4.2.1.jar) randoop.main.Main gentests --testclass=java.util.TreeSet --output-limit=100
But it throws an error saying it can load main class. any way I will try with the new distribution you linked and post again. Is it possible to create a new thread? Sorry for that too.

**Comment by mernst** [comment]
> the download link you sent me is slightly different than the one I found on my own on randoop page and the one that I found doesnot have all those file, only three jars. May be it can be made more accesible.

Can you please tell me the exact Randoop page that you found and where you found it?  What you told me does not give enough information to take action.

> But it throws an error saying it can load main class.

I'm not sure why it would throw an error saying it **can** load the main class.  An error saying it **cannot** load the main class seems more likely.  But, as described in the [manual's instructions for reporting a problem](https://randoop.github.io/randoop/manual/index.html#bug-reporting), please never give a vague English description of a problem.  Instead, paste the exact, full output.  Otherwise I cannot help you.

> Is it possible to create a new thread?

Follow the [manual's instructions for reporting a problem](https://randoop.github.io/randoop/manual/index.html#bug-reporting).  That is, click on "new issue" at https://github.com/randoop/randoop/issues .

**Comment by rickersilva** [comment]
I have been working with the instructions and files here
https://randoop.github.io/randoop/manual/index.html#getting_randoop

and the randoop installation zip linked there is in here
https://github.com/randoop/randoop/releases/download/v4.2.1/randoop-4.2.1.zip

As I encounter errors executing the command depicted in the manual I went to look for something else and got into a youtube video for an older version. That´s where the confusion arise, the video shopws the bin folder and did something weird. I no longer follow those instructions and decided to start over. 

I started a new discussion here: https://github.com/randoop/randoop/issues/644 to go ahead with this. thank you
