### ISSUE TITLE
Queries on Randoop

### ISSUE THREAD

**Issue by jnanesh123** [randoop/randoop#418]
Hi All,

while doing POC on randoop we came across below questions.

i am not sure this is the right platform to ask questions. if not, Please let me know where i can post these questions

1. is randoop generates multiple inputs only for primitive data types like string,Int etc.. or it can generate multiple inputs based on objects we provide as an input to method.

for ex: if method ABC takes three parameters as string A,int B,object xyz , now when we run randoop will it generates multiple combination of inputs for method ABC like 
1 ABC("we",12,null) 
2 ABC(" ",-1,(instance of xyz)  etc..

**Comment by mernst** [comment]
The answer to your question is yes.  The [second paragraph of the Randoop manual](https://randoop.github.io/randoop/manual/index.html#Introduction) gives an example of a test case generated by Randoop.  It contains code such as

```java
TreeSet t1 = new TreeSet(list);
Set s1 = Collections.synchronizedSet(t1);
```

where the argument to `synchronizedSet` is the result of a previous call generated by Randoop.  This also works when there are multiple arguments to a method.

For asking questions, there are also mailing lists, which are described in the [Getting help](https://randoop.github.io/randoop/manual/index.html#getting_help) section of the [Randoop manual](https://randoop.github.io/randoop/manual/).  You might want to look through the documentation first, since it answers common questions.  For questions not answered by the manual, please ask!
