### ISSUE TITLE
Single Assert Statement per Test Case

### ISSUE THREAD

**Issue by nathanila** [randoop/randoop#419]
The generated test cases are long and difficult to read.  Instead of generating long test cases with many Assert statements in each test case, generate several test cases with 1 Assert statement per test case.  This will make the test cases short and easy to read.  It will make each test case focused on testing 1 property and hence make it easy to understand.

Version: 4.1.0
Command: `java -classpath randoop-all-4.1.0.jar;... randoop.main.Main gentests --classlist=myclasses.txt --time-limit=60`

**Comment by mernst** [comment]
If you have a patch that achieves this, please submit a pull request.

One potential concern is that Randoop would output many more tests than it does currently:  if there is currently a test with 10 assertions, the variant of Randoop that you propose might have 10 times as many tests, each with one assertion.

You say that the generated tests are long and difficult to read (which is true!), but you don't say why that is a problem.  What is the use case for examining the test cases?  Ordinarily, a user reads a test only when it fails.  A failing test can be [minimized](https://randoop.github.io/randoop/manual/#minimize) so that it is short and contains only a single test failure.

**Comment by nathanila** [comment]
I do not have a patch for this.  I realize that this means there would be 10 times more tests.

I would like to take the tests and give them proper names.  I would like to verify that each test is actually needed.  In other words, I do not trust the automation.

**Comment by mernst** [comment]
I see.  The definition of "actually needed" is tricky, because there are many different metrics for test quality.  You could use line coverage, or branch coverage, or some stronger type of structural (code) coverage.  You could use value coverage.  You could use mutation analysis.  Etc.  If your definition differs from Randoop's, then you will surely find that it generates too few or too many tests according to your definition.

For translating the tests to TestNG, I think it would easier, cleaner, and useful to more people to add an option to Randoop to have it generate the TestNG files.  We would welcome such a patch!

I'll close this issue for now, because it seems to encompass multiple different enhancements to Randoop, not just one.  But feel free to contribute changes that address your needs -- they are likely to help other users as well.  Thanks!
