### ISSUE TITLE
Name Test Methods Better

### ISSUE THREAD

**Issue by nathanila** [randoop/randoop#422]
Current the tests are named `test_###`.  Please provide better names for the test cases.  For example, name the test based on the class under test (if more than 1 class), the method under test and the property of the method being tested.  This will improve the readability of the code, the intent of the test and hence improve the maintainability of the test.

The reason programmers use Randoop is to reduce the amount of work they have to do.  Sure automatically generating the test cases saves a lot of time, but that is only part of the cost of the code.  The other cost of the code is maintaining the test cases as the code under test evolves.

Version: 4.1.0
Command: `java -classpath randoop-all-4.1.0.jar;... randoop.main.Main gentests --classlist=myclasses.txt --time-limit=60`

**Comment by mernst** [comment]
As explained in the introduction (and clarified in https://github.com/randoop/randoop/commit/d497d8acbec1a46c75f03be085cbb135770867b0), developers are not expected to read and maintain Randoop tests.  Randoop takes the place of developer work to maintain the test suite.

You seem to be using Randoop in a different way than other programmers.  That's neat!
If you want changes to Randoop, it would be very helpful to explain how you and your team are using it and what you really want to do.  For example, why is it important to read, understand, and maintain the test cases rather than regenerating them as needed?  That is more motivating than a feature request without context.

The changes you suggest sound fine in general.
I don't understand what you mean by "the property of the method being tested", and Randoop does not have an "intent" for any test it generates.  Please feel free to contribute a patch.  I'll close this for now so that we don't clutter the issue tracker with random feature requests, but we can have a conversation to clarify the request.

**Comment by nathanila** [comment]
I do not trust automatically generated tests.  I have several classes that are so well written that Randoop does not flag any failing tests.  However, the classes have bugs in them.  Randoop creates tests that pass and would fail if the bugs were fixed.  This makes the Randoop tests dangerous since future changes will fail and the programmer will then have to spend a lot of time to figure out the Randoop test and fix it.

My intent is to have Randoop or some other tool generate test cases that I can read, understand, incorporate into my test suite and maintain.  The tool should generate easy to read and understand test cases since I have to understand what the test case is testing before I will approve it for inclusion in my test suite.  I also want to review the test case code to see if it exposes a bug.

Randoop output is hard to read.  You might as well output .class files if you do not intend to have humans read the Randoop Java code.
