### ISSUE TITLE
Can randoop test on jar package?

### ISSUE THREAD

**Issue by raymondlingxiao** [randoop/randoop#473]
Hi,

I wonder if Randoop has supported directly use the jar files as the test inputs instead of using `--classlist`?
I've looked into the documentation, but none of it has mentioned this feature. So what should I do if I want to use it to directly test on a `JAR file`?
Thanks! 
@mernst @carloslima @thadguidry @linozem @peskal

**Comment by mernst** [comment]
This is a great suggestion -- in fact, it has been requested before, so it is on the development roadmap

In addition to "test everything in this jar file", the feature "test everything in this jar file that is in a specific package or a subpackage" also makes sense, because fat jars often contain libraries that there is no point in testing directly.

If you are willing to work on this issue, that would be welcome.  It should not be too hard to implement.  Ask if you need help.

**Comment by mernst** [comment]
I have pushed a change that adds command-line arguments --testjar, --omit-classes, and --omit-classes-file.  Could you try it and let me know if you have any problems?
