### ISSUE TITLE
How detailed does --classlist need to be?

### ISSUE THREAD

**Issue by chamkank** [randoop/randoop#628]
Hi there, I'm trying to figure out how detailed the `--classlist` parameter was when Randoop generated the below example from the documentation:

```
  // This test shows that the JDK collection classes
  // can create an object that is not equal to itself.
  @Test
  public static void test1() {
    LinkedList list = new LinkedList();
    Object o1 = new Object();
    list.addFirst(o1);
    TreeSet t1 = new TreeSet(list);
    Set s1 = Collections.synchronizedSet(t1);
    org.junit.Assert.assertTrue(s1.equals(s1));
  }
```
From my understanding, you would need to include `Collections, TreeSet, Object, LinkedList` in the class list. However, the documentation seems to imply that the classes that were included were just `Collections, TreeSet`.

Which one is correct? If it's the latter, how does Randoop know to generate a new `LinkedList` and a new `Object`? I've read into seed sequences but from understanding those only populate the component pool with primitive sequences (for example: `int i = 0;`).

Any help would be appreciated, thank you!

**Comment by mernst** [comment]
To create such a test, provide all the methods in the JDK.  (Actually, just the ones in java.lang and java.util is probably enough.)  Programmers don't generally want to test just one class -- if they knew the class that had an error, they wouldn't need to create the tests!  A benefit of Randoop is that it explores all of a program.  It is generally counterproductive to try to direct it.

> the documentation seems to imply that the classes that were included were just Collections, TreeSet.

Can you tell me where it implies that?  I don't see it, which is why your explanation will help me.

**Comment by chamkank** [comment]
Thanks for the quick reply! The part that confused me was [here](https://randoop.github.io/randoop/manual/index.html#example_collections). It mentioned generating tests for `Collections` and said that the class list was just `Collections, TreeSet`.

Now that I look at it, it doesn't mention that it's linked to the `test1` example further up in the documentation. But it seemed similar enough that I assumed that the same class list would be used (my bad).

**Comment by mernst** [comment]
Thanks for pointing that out.  I will tweak the manual to be a bit clearer.
