### ISSUE TITLE
Support for targeting a specific class under test

### ISSUE THREAD

**Issue by rjust** [randoop/randoop#66]
Currently, Randoop can't target a specific unit (i.e., generating unit tests for a single class under test (CUT), if this unit has dependencies. Randoop uses a bottom-up approach to generate tests, and therefore requires all dependencies to be tested as well. Some of the generated tests might, however, not test the actual CUT -- neither directly nor indirectly. This has the following drawbacks:
1) An unnecessarily large test suite.
2) Run time of Randoop needs to be significantly longer to achieve a high level of coverage on the CUT.

Ideally, Randoop would prune the search space of method calls with some sort of top-down dependency analysis, starting with the CUT. Even if no dependency analysis is used, at least a filter that removes all irrelevant tests (e.g., the ones that don't execute a single statement in the CUT) during or after test generation would be great.

**Comment by mernst** [comment]
Thanks for the feature request.

This can already be achieved through command-line options to Randoop.  If you desire to focus Randoop on tests for class C, then you can determine every class that C depends upon, and pass them to Randoop.  Your suggestion of filtering tests that don't touch C would be an added benefit.  It could be nice to create an external program or add a command-line argument to Randoop to automate this.

This feature request states a desired feature, but it does not state a reason for the feature, such as an end-user use case or a programmer goal.  A programmer generally wants to generate tests for an entire program, not just one class of that program.  Even if a programmer has changed only class C, the programmer still needs to generate tests for every class in the program that may depend on class C.

My interpretation of the feature request is that it is intended to help researchers experiment and compare with other test-generation tools that can be targeted to generate tests for a specific class.  Other test-generation tools have this feature, so it would be convenient for Randoop to have it as well.

However, the reason that other tools have this feature is that those tools are unscalable.  Those tools don't work well on the programs that programmers want to test, and so the researchers use an unrealistic approach of generating tests for a single class in order to work around the limitations of those tools or in order to make the experiments run faster.  It would be better for the researchers to do more realistic experiments.  That would lead to better science than changing Randoop so that it mimics the workaround of focusing on a single class.

Experiments that focus on a single class should pass command-line arguments to focus Randoop as described above (and/or prune after generation as you suggested); both are achievable by writing external programs, and we welcome contributions of such programs.  However, we'll keep this feature request open to simplify that process, or to hear from others who may desire this feature.

Thanks again for the feature request.

**Comment by bjkeller** [comment]
It might have been a little hard to spot and it is a bit awkward, but this ability was already in Randoop from before v.2.  It has been possible to restrict the output tests by using the --test-classes command-line argument. This argument takes a regex of class names that must be included in each test included in the output.  

In v.2.1.0 this argument's name will change to distance it a little from --testclass.

I'm closing this issue, though we might consider whether linking this to the classes specified by --testclass would make sense.
