### ISSUE TITLE
Resetting values of static variables

### ISSUE THREAD

**Issue by rchakra3** [randoop/randoop#86]
I encountered an interesting problem while using randoop to generate tests for classes with static variables.

Randoop's tests set the value of these static variables to some unrelated/invalid values. 
The Randoop generated tests then successfully catch these exceptions. 
The problem is that when the repo's original test cases run after the Randoop tests, and test the classes with the static variables (without modifying the values), they encounter exceptions.

For example, this was the class for which I generated tests: 
[XmlReader.java](https://github.com/rometools/rome/blob/master/rome/src/main/java/com/rometools/rome/io/XmlReader.java)

These were the tests that failed because they expected the value of variable `defaultEncoding` to be `null`:
[XmlReaderTest.java](https://github.com/rometools/rome/blob/master/rome/src/test/java/com/rometools/rome/io/XmlReaderTest.java)

Is this expected behavior? I feel it would make sense to reset the values of static variables to their defaults in the generated test cases.

**Comment by mernst** [comment]
Yes, this is expected behavior.
To avoid this problem, you can run Randoop's tests in a separate JVM, or run Randoop's tests last, or avoid calling Randoop on methods with global side effects as described in the manual section section on [flaky tests](https://randoop.github.io/randoop/manual/index.html#flaky-tests).

It would be possible to have Randoop undo its side effects.  Feel free to submit a pull request with an implementation of such a feature!  Note that doing so could break the program under test by violating its contracts, so it would need to be enabled/disabled via a command-line option so that users can choose whether to do so.

**Comment by bjkeller** [comment]
Just along the lines of Mike's comment --- the test you have is implicitly assuming a clean load of the class, or at least good behavior on the part of other code. The first needs a clean JVM, and the second can be emulated by omitting the field from consideration when you run Randoop.

**Comment by rchakra3** [comment]
@mernst @bjkeller Thanks! 

@mernst I'd love to try and submit a PR. What would you say is a good approach to have Randoop undo its side effects? keep track of the original values of class variables and then reset them at the end of the generated tests? or did you have something else in mind?

**Comment by bjkeller** [comment]
@rchakra3  You only need to capture the values of static fields collected by randoop.reflection.OperationExtractor, though the cleanest approach for you may be to implement another randoop.reflection.ClassVisitor and add it to the ReflectionManager during setup in randoop.main.GenTests. I assume you eventually want to get all of this value wrangling into the tests, so you'd need to figure out what your `@BeforeClass` and `@AfterClass` methods would look like, and then add the generation code to randoop.junitFileWriter.
